_wandb:
    value:
        cli_version: 0.24.0
        e:
            rflhhfa1fhqi8oj4idsq9nt0e35czapb:
                codePath: RNN_AND_LSTM_Electric\train_model.py
                codePathLocal: train_model.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "180084535296"
                        used: "64748851200"
                email: 766993892@qq.com
                executable: R:\Program Files\Python312\python.exe
                git:
                    commit: 3129980d28b456833dbb15d5e724dea09bf27f0d
                    remote: https://github.com/lushij/AI.git
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-b1126df8-b43a-bf93-04d0-36113fa76b83
                host: LAPTOP-RJ8D2L7U
                memory:
                    total: "16471552000"
                os: Windows-10-10.0.19045-SP0
                program: D:\AI\RNN_AND_LSTM_Electric\train_model.py
                python: CPython 3.12.3
                root: D:\AI\RNN_AND_LSTM_Electric
                startedAt: "2026-01-30T11:30:16.787723Z"
                writerId: rflhhfa1fhqi8oj4idsq9nt0e35czapb
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
accumulation_steps:
    value: 4
batch_size:
    value: 64
epochs:
    value: 20
hidden_size:
    value: 128
learning_rate:
    value: 0.01
max_grad_norm:
    value: 1
num_layers:
    value: 2
window_size:
    value: 96
